README.md
lib/chusaku.rb
lib/chusaku/routes.rb
lib/chusaku/version.rb
test/chusaku_test.rb
test/mock/rails.rb
test/routes/routes_test.rb

Previously, each `@route` comment displayed only one verb like such:
```ruby
```
But with this PR, multiple verbs are allowed like the following:
```ruby
```
Brackets are now used to wrap verbs regardless of how many there are as well. They are easier to parse when glancing at a `@route` comment.

Display multiple verbs

---

chusaku.gemspec
lib/chusaku.rb

This PR adds [ruby-progressbar](https://github.com/jfelchner/ruby-progressbar) to Chusaku and uses it instead of a slew of `puts` statements.

Add progress bar

---

chusaku.gemspec
lib/chusaku.rb

This PR removes `ruby-progressbar` as a dependency because:
1. The less dependencies the better so more apps can incorporate the latest version of Chusaku
2. It's more useful to have a full output of all annotated files in the end anyway

Remove `ruby-progressbar` and favor plain output

---

bin/chusaku
lib/chusaku.rb
lib/chusaku/cli.rb
lib/chusaku/parser.rb
test/chusaku_test.rb
test/cli_test.rb
test/mock/app/controllers/api/burritos_controller.rb
test/mock/file.rb
test/mock/rails.rb
test/parser/parser_test.rb
test/routes/routes_test.rb
test/test_helper.rb

Hi!
Thank you for the great tool. We recently adopted it and very happy with the result. One thing we stumbled upon is automation.
Current behaviour is to annotate everything and report all of the files. If someone added new route and did not know that `chusaku` needs to be invoked, we'll have synchronisation issue between comments and code.
There are couple solutions I see:
- run it on CI and fail if new annotations added;
- run in the git hook and prevent commit/push if new annotation added;
To be able to do it we need a way to report back on changes (status code, what was changed).
I added couple of flags to be able to achieve this.
What do you think?

Add CLI flags

---

lib/chusaku/routes.rb
test/mock/rails.rb

Older versions of Rails (e.g. 4.2) return regular expressions instead of strings for a route verb. This results in Chusaku outputting routes that may look like:
```ruby
```
Account for said regular expressions that may be returned by a route verb, extract HTTP verbs being used, and remove duplicates.

Account for regular expressions containing multiple verbs

---

chusaku.gemspec
lib/chusaku.rb

Files that end up shorter than they were originally will no longer have "remnants" of what the previous contents were.
Due to Chusaku using `File.open(file, 'r+')`, files that ended up shorter as a result of the executable kept old file contents trailing after the newly written contents.
Switch to using `w` mode with `File`.

Fix invalid file content trails

---

lib/chusaku.rb
lib/chusaku/routes.rb
test/chusaku_test.rb
test/mock/rails.rb
test/routes_test.rb

Route may be declared with `defaults: {some: param}`, which is necessary information to understand how it is called in this case.
Some examples (from real codebase, with slightly changed route names for anonymization):
**case 1: "by id" vs "all"**
```ruby
get '/users/:id/events', controller: :users, action: :events
get '/users/all/events', controller: :users, action: :events, defaults: {all: true}
```
Now, controller method events has this annotation:
```ruby
def events
```
...which requires digging deep in code to understand how in "all" case it would understand it is `all` (or looking into `routes.rb`, which Chusaku helps to avoid). With proposed addon:
```ruby
def events
```
**case 2: this or that**
```ruby
get '/dashboard', controller: :dashboard, action: :index, {context: 'general'} …
```

Show defaults in controller annotation

---

chusaku.gemspec

this allows for consumers to remove the rails dependency if they only need pieces of rails
This was brought on by the issue here ( https://twitter.com/nateberkopec/status/1374722404228853762 )
And since we are not using activestorage we could simply remove it, however this gem keeps pulling rails back in (when not needed)

Depend on railties instead of rails

---

lib/chusaku.rb
test/chusaku_test.rb

Addresses #20.
Implements the following CLI messages:
> The following files would be annotated without `—dry-run`: ...
> Annotated ...
>
> Exiting with status code 1.
> Annotations missing in the following files: ...
>
> Run `chusaku` to annotate them. Exiting with status code 1.

Improve CLI output

---

README.md
lib/chusaku.rb
lib/chusaku/cli.rb
lib/chusaku/parser.rb
test/chusaku_test.rb
test/cli_test.rb
test/parser_test.rb

#24.
This PR adds a `--verbose` flag to Chusaku and outputs changes in detail when used with that flag.
Example output:
````
[test/mock/app/controllers/api/burritos_controller.rb:4]
Before:
```ruby
```
After:
```ruby
```
[test/mock/app/controllers/api/burritos_controller.rb:5]
Before:
```ruby
def create; end
```
After:
```ruby
def create; end
```
[test/mock/app/controllers/api/tacos_controller.rb:4]
Before:
```ruby
def show; end
```
After:
```ruby
def show; end
```
[test/mock/app/controllers/api/tacos_controller.rb:6]
Before:
```ruby
```
After:
```ruby
```
[test/mock/app/controllers/api/tacos_controller.rb:10]
Before:
```ruby
def create; end
```
After:
```ruby
def create; end
```
[test/mock/app/controllers/api/tacos_controller.rb:12]
Before:
```ruby
```
After:
```ruby
``` …
```

Add more detailed output with `--verbose` flag

---

lib/chusaku.rb
test/chusaku_test.rb
test/mock/rails.rb
test/test_helper.rb

Fixes #27.
There was a bug in which `Nothing to annotate.` was not in the output of Chusaku runs when it should have been. This was due to #25 where more detailed changes started getting tracked in `chusaku.rb`.
This PR adds a test for and fixes this bug.

Fix no "nothing to annotate" bug

---

README.md
test/mock/rails.rb

As the title states, this updates the README so that the link to the blog post isn't broken. I suspect this link broke/unbroke a couple times as I transitioned to/from using Remix and Jekyll as the underlying tech powering my blog.

Fix broken blog post link in README

---

lib/chusaku/routes.rb
test/chusaku_test.rb
test/mock/app/controllers/api/cakes_controller.rb
test/mock/rails.rb
test/routes_test.rb

Fixes #34.
This PR fixes an issue where Chusaku doesn't annotate a name for a route even when its path has one.

fix: missing route names

---

test/chusaku_test.rb

Fix a typo in an `assert`. More details: https://github.com/nshki/chusaku/pull/37#issuecomment-1704390602

fix typo assert

---

README.md
lib/chusaku.rb
lib/chusaku/cli.rb
test/chusaku_test.rb
test/cli_test.rb
test/mock/rails.rb

Hi! Thank you for this gem!
We're using [packs-rails](https://github.com/rubyatscale/packs-rails) in our rails app, which means we've got controllers outside the `/app` directory.
If you think it makes sense, could you consider supporting this use-case? I found this way to be the most minimal change required to support it.
Thank you!

Also look for controllers outside /app

---

.github/workflows/testing.yml
.gitignore
README.md
lib/chusaku.rb
lib/tasks/chusaku.rake

Closes #40.
As the title states, this PR adds a Rake task for Chusaku. This allows users to use a Rake task to execute Chusaku in addition to the executable it ships with like such:
```sh
bin/rake chusaku -- --dry-run
```
Loading the gem's Rake tasks is a matter of adding a one-liner to a project's `Rakefile`:
```ruby
Chusaku.load_tasks
```
Users will need to update their `Gemfile` such that Chusaku isn't being required with the `require: false` flag:
```ruby
gem "chusaku", require: false
gem "chusaku"
```

feat: add Rake task

---

lib/chusaku.rb
test/chusaku_test.rb

Before:
```
❯ bundle exec rake dev:annotate
Chusaku has finished running.
Model files unchanged.
❯ bundle exec rake dev:annotate
Nothing to annotate.
Model files unchanged.
```
After:
```
❯ bundle exec rake dev:annotate
Chusaku has finished running.
Model files unchanged.
❯ bundle exec rake dev:annotate
Controller files unchanged.
Model files unchanged.
```
I've also preserved the newline before the final output line if `--verbose` is passed.
Resolves #42

fix: improve cli output

---

.github/workflows/linting.yml
.github/workflows/testing.yml
README.md
lib/chusaku.rb
lib/chusaku/cli.rb
test/chusaku_test.rb

Closes #43.
This PR changes/fixes the behavior of `--verbose` such that instead of printing out all changes on the given run, it will list out all changed files.

fix: unnecessary verbose output

---

README.md
lib/chusaku.rb
lib/chusaku/cli.rb
test/chusaku_test.rb

Closes #53.
This PR introduces a new `--exclusion-pattern` flag to enable users to customize the controller exclusion glob. By default, `--exclusion-pattern` will ignore all `*_controller.rb` files present in the top-level `vendor/` directory.

feat: add `--exclusion-pattern` flag

---

test/chusaku_test.rb
test/cli_test.rb
test/parser_test.rb
test/routes_test.rb

This refactors the test suite to use [Minitest's spec styles](https://github.com/minitest/minitest?tab=readme-ov-file#specs-) instead of the traditional [unit test styles](https://github.com/minitest/minitest?tab=readme-ov-file#unit-tests-). This doesn't change the gem's functionality at all, it only updates the test suite for, in my opinion, better readability.

test: use Minitest spec style

---

lib/chusaku.rb
lib/chusaku/routes.rb
test/chusaku_test.rb
test/mock/app/controllers/api/cakes_controller.rb
test/mock/app/controllers/api/croissants_controller.rb
test/mock/app/controllers/pastries_controller.rb
test/mock/rails.rb
test/routes_test.rb

Closes #57.
This PR updates Chusaku to account for controller actions that are passed down through object-oriented class inheritance. The high-level changes include:
- Store `#source_location` data in `Chusaku::Routes` as `source_path`.
- Map source paths to corresponding actions data and loop over that to annotate files.
- Update tests.

fix: inherited actions

---

.github/workflows/linting.yml
.github/workflows/testing.yml
chusaku.gemspec

With the Christmas release of Ruby 3.4, this is to make sure the gem's CI is updated with it in mind. Also includes a drive-by update of development dependencies.

build: account for Ruby v3.4
